# Generated by Django 2.1.4 on 2019-01-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='imgage',
            new_name='image',
        ),
    ]
