# Generated by Django 2.1.5 on 2019-02-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('locations', models.CharField(max_length=250)),
                ('cp', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('biography ', 'Biography'), ('classic', 'Classic'), ('comics', 'Comics/Graphic novel'), ('crime', 'Crime/detective'), ('essay ', 'Essay'), ('fable', 'Fable'), ('fairy-tailr', 'Fairy tale'), ('fan-fiction', 'Fan fiction'), ('fantasy', 'Fantasy'), ('folklore', 'Folklore'), ('historical-fiction', 'Historical fiction'), ('horror', 'Horror'), ('humor', 'Humor'), ('journalism', 'Journalism'), ('lab-report ', 'Lab report'), ('legend', 'Legend'), ('magical-realism', 'Magical realism'), ('manual', "Owner's manual"), ('memoir', 'Memoir'), ('meta-fiction', 'Meta fiction'), ('mystery', 'Mystery'), ('mythology', 'Mythology'), ('mythopoeia', 'Mythopoeia'), ('narrative-nonfiction', 'Narrative nonfiction/personal narrative'), ('picture-book', 'Picture book'), ('realistic-fiction', 'Realistic fiction'), ('reference', 'Reference book'), ('science-fiction', 'Science fiction'), ('self-help', 'Self-help book'), ('short-story', 'Short story'), ('speech', 'Speech'), ('suspense', 'Suspense/thriller'), ('swashbuckler', 'Swashbuckler'), ('tall-tale', 'Tall tale'), ('textbook ', 'Textbook'), ('western', 'Western')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.UserDetails'),
        ),
    ]
