# Generated by Django 2.1.4 on 2019-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='language_code',
            field=models.CharField(max_length=3),
        ),
    ]
