# Generated by Django 2.1.4 on 2019-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190116_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(related_name='collections', to='index.Book'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='books',
            field=models.ManyToManyField(related_name='series', to='index.Book'),
        ),
    ]
